### ISSUE TITLE
使用 DHT 代替 Twister

### ISSUE THREAD

**Issue by iovxw** [acgsh/acgsh#1]
可以直接让上传者将种子签名来验证身份

签名请参考: http://www.bittorrent.org/beps/bep_0035.html

然后发布到 DHT 即可（就算不按这个要求，一般上传者也都会主动发布到 DHT）

到时只需做一个 DHT 爬虫，下载完种子后，只抓取可信签名的发布到页面

成本相较使用 Twister 低很多，对上传者的要求也不大，可以写个一键签名工具

唯一问题是介绍，但是也可以将介绍直接打包在种子内，添加字段就可以了

**Comment by acgsh** [comment]
从底层开始开发肯定会好很多，但是没有足够的人力啊。
可以先用着Twister，等开发实力够了再切换底层。

**Comment by iovxw** [comment]
问题是，等实力够了，现有方案用的人也就多了

难道要他们再次转变习惯吗

2016年1月7日 05:46，acgshare <notifications@github.com>写道：
从底层开始开发肯定会好很多，但是没有足够的人力啊。
可以先用着Twister，等开发实力够了再切换底层。

---

**Comment by acgsh** [comment]
前端用户界面是不变的，只是后端分布式数据库变了。只需要少数发布者改变习惯，应该还好吧。而且可以同时兼容多种后端，慢慢过渡。
